name: Fetch index data from NOAA
on:
  schedule:
    - cron:  '5 19 11 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch data
        run: python fetch.py
      - name: Push updates
        run: |
          git --no-pager diff
          git config user.name Will Holmgren
          git config user.email william.holmgren@gmail.com
          git commit -a -m "update index data"
          git push
